spring.application.name=StoreManagement
# Docker Compose Support
spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yml
spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.readiness.wait=ALWAYS

# Server Port
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/store_management
spring.datasource.username=postgres
spring.datasource.password=postgres
# JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.prefetch=10
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0

# Módulo Usuarios (External Service)
modulo.usuarios.base-url=http://localhost:8081
modulo.usuarios.timeout.connect=2000
modulo.usuarios.timeout.read=5000

# Resilience4j - CircuitBreaker
resilience4j.circuitbreaker.instances.moduloUsuarios.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.moduloUsuarios.slow-call-rate-threshold=50
resilience4j.circuitbreaker.instances.moduloUsuarios.slow-call-duration-threshold=2s
resilience4j.circuitbreaker.instances.moduloUsuarios.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.moduloUsuarios.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.moduloUsuarios.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.moduloUsuarios.sliding-window-size=10

# JWT
jwt.secret=Nx7mVq9jK2pL4wR8tY3zA5bC7dE9fG1hJ0kM4nP6qR8sU0vW2xY4zA6bC8dE0f
jwt.expiration=86400000
resilience4j.retry.instances.moduloUsuarios.wait-duration=500ms
resilience4j.retry.instances.moduloUsuarios.retry-exceptions[0]=java.net.SocketTimeoutException
resilience4j.retry.instances.moduloUsuarios.retry-exceptions[1]=org.springframework.web.client.ResourceAccessException

# Async Thread Pool
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=100

# Actuator & Prometheus
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

